package com.yloquen.tools
{
	public class Presets
	{
		private static var ptr:int = 0;

		private static const PRESETS:Array =
		[
			{"multiTweens":[{"orderingFunc":"RANDOM","durationDistrib":"Bounce.easeIn","randomEase":true,"prop":"rotation","distribFunc":"Cubic.easeOut","firstVal":"-4.620","tweenEase":"Quad.easeIn","lastVal":"1.260","masterDelay":"0.489","firstDuration":"0.484","delayDuration":"1.968","lastDuration":"0.714","delayDistrib":"Elastic.easeOut"},{"orderingFunc":"SQR","durationDistrib":"Sine.easeOut","randomEase":false,"prop":"y","distribFunc":"Quad.easeOut","firstVal":"-88.000","tweenEase":"Sine.easeInOut","lastVal":"319.000","masterDelay":"0.335","firstDuration":"0.180","delayDuration":"0.414","lastDuration":"0.635","delayDistrib":"Expo.easeOut"},{"orderingFunc":"SQR","durationDistrib":"Quad.easeInOut","randomEase":true,"prop":"alpha","distribFunc":"Cubic.easeOut","firstVal":"0.000","tweenEase":"Linear.easeIn","lastVal":"0.000","masterDelay":"0.347","firstDuration":"0.319","delayDuration":"0.562","lastDuration":"0.146","delayDistrib":"Elastic.easeInOut"},{"orderingFunc":"SIN_1","durationDistrib":"Bounce.easeIn","randomEase":false,"prop":"scaleX","distribFunc":"Circ.easeIn","firstVal":"-6.650","tweenEase":"Circ.easeIn","lastVal":"0.750","masterDelay":"0.358","firstDuration":"0.522","delayDuration":"1.968","lastDuration":"0.679","delayDistrib":"Cubic.easeOut"}],"pivot":{"y":"0.000","x":"0.000"},"randomPivotPerChar":true},
			{"multiTweens":[{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Quart.easeInOut","randomEase":false,"prop":"y","distribFunc":"Quad.easeInOut","firstVal":"-162.000","tweenEase":"Elastic.easeIn","lastVal":"108.000","masterDelay":"0.858","firstDuration":"0.407","delayDuration":"1.282","lastDuration":"0.648","delayDistrib":"Bounce.easeOut"},{"orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Sine.easeOut","randomEase":false,"prop":"alpha","distribFunc":"Elastic.easeIn","firstVal":"0.000","tweenEase":"Expo.easeIn","lastVal":"0.000","masterDelay":"0.230","firstDuration":"0.669","delayDuration":"2.596","lastDuration":"0.580","delayDistrib":"Quad.easeInOut"},{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Cubic.easeInOut","randomEase":false,"prop":"scaleX","distribFunc":"Quart.easeIn","firstVal":"-3.200","tweenEase":"Circ.easeInOut","lastVal":"22.800","masterDelay":"0.393","firstDuration":"0.948","delayDuration":"2.436","lastDuration":"0.382","delayDistrib":"Bounce.easeOut"},{"orderingFunc":"SIN_1","durationDistrib":"Quint.easeInOut","randomEase":false,"prop":"x","distribFunc":"Linear.easeIn","firstVal":"-33.000","tweenEase":"Quint.easeInOut","lastVal":"33.000","masterDelay":"0.234","firstDuration":"0.975","delayDuration":"1.833","lastDuration":"0.346","delayDistrib":"Sine.easeOut"},{"orderingFunc":"SQR","durationDistrib":"Quad.easeInOut","randomEase":false,"prop":"color","distribFunc":"Quad.easeInOut","firstVal":"6442450.560","tweenEase":"Sine.easeInOut","lastVal":"7918845.480","masterDelay":"0.225","firstDuration":"0.289","delayDuration":"3.000","lastDuration":"0.625","delayDistrib":"Elastic.easeInOut"}],"pivot":{"y":"0.500","x":"0.500"},"randomPivotPerChar":false},
			{"randomPivotPerChar":false,"multiTweens":[{"prop":"rotation","durationDistrib":"Cubic.easeIn","distribFunc":"Quart.easeInOut","tweenEase":"Back.easeInOut","randomEase":false,"firstVal":"-1.830","orderingFunc":"SIN_2","lastVal":"7.890","masterDelay":"0.986","firstDuration":"0.963","delayDuration":"1.754","lastDuration":"0.488","delayDistrib":"Bounce.easeIn"},{"prop":"alpha","durationDistrib":"Sine.easeIn","distribFunc":"Elastic.easeOut","tweenEase":"Sine.easeInOut","randomEase":false,"firstVal":"0.000","orderingFunc":"SIN_2","lastVal":"0.000","masterDelay":"0.450","firstDuration":"0.471","delayDuration":"1.578","lastDuration":"0.230","delayDistrib":"Cubic.easeIn"}],"pivot":{"y":"1.640","x":"2.047"}},
			{"multiTweens":[{"orderingFunc":"RANDOM_WORD_ORDER","durationDistrib":"Back.easeIn","randomEase":false,"prop":"scaleY","distribFunc":"Cubic.easeIn","firstVal":"-23.050","tweenEase":"Cubic.easeInOut","lastVal":"27.800","masterDelay":"0.030","firstDuration":"0.958","delayDuration":"2.211","lastDuration":"0.627","delayDistrib":"Quad.easeOut"},{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Quint.easeOut","randomEase":false,"prop":"alpha","distribFunc":"Cubic.easeIn","firstVal":"0.000","tweenEase":"Quad.easeInOut","lastVal":"0.000","masterDelay":"0.684","firstDuration":"0.258","delayDuration":"3.206","lastDuration":"0.365","delayDistrib":"Quad.easeOut"},{"orderingFunc":"RANDOM_WORD_ORDER","durationDistrib":"Back.easeIn","randomEase":false,"prop":"scaleX","distribFunc":"Cubic.easeIn","firstVal":"-23.050","tweenEase":"Cubic.easeInOut","lastVal":"27.800","masterDelay":"0.030","firstDuration":"0.958","delayDuration":"2.211","lastDuration":"0.627","delayDistrib":"Quad.easeOut"},{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Bounce.easeIn","randomEase":true,"prop":"x","distribFunc":"Elastic.easeInOut","firstVal":"-181.000","tweenEase":"Back.easeInOut","lastVal":"189.000","masterDelay":"0.386","firstDuration":"0.682","delayDuration":"0.928","lastDuration":"0.361","delayDistrib":"Circ.easeOut"},{"orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Quad.easeInOut","randomEase":false,"prop":"skewX","distribFunc":"Linear.easeIn","firstVal":"-2.250","tweenEase":"Quart.easeIn","lastVal":"0.990","masterDelay":"0.750","firstDuration":"0.887","delayDuration":"3.000","lastDuration":"0.851","delayDistrib":"Circ.easeIn"}],"pivot":{"y":"0.000","x":"0.000"},"randomPivotPerChar":true},
			{"multiTweens":[{"orderingFunc":"MODULO_3","durationDistrib":"Sine.easeIn","randomEase":false,"prop":"scaleY","distribFunc":"Back.easeIn","firstVal":"-20.700","tweenEase":"Cubic.easeIn","lastVal":"20.500","masterDelay":"0.048","firstDuration":"0.720","delayDuration":"3.000","lastDuration":"0.937","delayDistrib":"Elastic.easeOut"},{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Quint.easeOut","randomEase":false,"prop":"rotation","distribFunc":"Back.easeInOut","firstVal":"-1.890","tweenEase":"Quad.easeInOut","lastVal":"4.980","masterDelay":"0.314","firstDuration":"0.724","delayDuration":"1.932","lastDuration":"0.946","delayDistrib":"Expo.easeInOut"},{"orderingFunc":"MODULO_2","durationDistrib":"Linear.easeIn","randomEase":false,"prop":"y","distribFunc":"Quart.easeIn","firstVal":"-168.000","tweenEase":"Cubic.easeIn","lastVal":"275.000","masterDelay":"0.495","firstDuration":"0.367","delayDuration":"3.000","lastDuration":"0.435","delayDistrib":"Back.easeIn"},{"orderingFunc":"MODULO_2","durationDistrib":"Elastic.easeInOut","randomEase":true,"prop":"alpha","distribFunc":"Circ.easeInOut","firstVal":"0.000","tweenEase":"Bounce.easeOut","lastVal":"0.000","masterDelay":"0.011","firstDuration":"0.619","delayDuration":"3.000","lastDuration":"0.472","delayDistrib":"Quad.easeOut"},{"orderingFunc":"MODULO_3","durationDistrib":"Sine.easeIn","randomEase":false,"prop":"scaleX","distribFunc":"Back.easeIn","firstVal":"-20.700","tweenEase":"Cubic.easeIn","lastVal":"20.500","masterDelay":"0.048","firstDuration":"0.720","delayDuration":"3.430","lastDuration":"0.937","delayDistrib":"Elastic.easeOut"},{"orderingFunc":"SIN_2","durationDistrib":"Linear.easeIn","randomEase":false,"prop":"x","distribFunc":"Elastic.easeIn","firstVal":"-152.000","tweenEase":"Bounce.easeOut","lastVal":"394.000","masterDelay":"0.795","firstDuration":"0.971","delayDuration":"3.000","lastDuration":"0.777","delayDistrib":"Cubic.easeIn"},{"orderingFunc":"SIN_1","durationDistrib":"Quad.easeOut","randomEase":false,"prop":"color","distribFunc":"Cubic.easeIn","firstVal":"3481272.112","tweenEase":"Sine.easeOut","lastVal":"4848615.135","masterDelay":"0.987","firstDuration":"0.494","delayDuration":"3.873","lastDuration":"0.477","delayDistrib":"Cubic.easeIn"}],"pivot":{"y":"2.096","x":"1.642"},"randomPivotPerChar":false},
			{"multiTweens":[{"orderingFunc":"RANDOM","durationDistrib":"Linear.easeInOut","randomEase":false,"prop":"scaleY","distribFunc":"Cubic.easeOut","firstVal":"-26.000","tweenEase":"Bounce.easeOut","lastVal":"25.950","masterDelay":"0.969","firstDuration":"0.728","delayDuration":"0.547","lastDuration":"0.226","delayDistrib":"Cubic.easeIn"},{"orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Sine.easeInOut","randomEase":false,"prop":"rotation","distribFunc":"Quint.easeInOut","firstVal":"-1.560","tweenEase":"Expo.easeInOut","lastVal":"8.130","masterDelay":"0.032","firstDuration":"0.541","delayDuration":"0.412","lastDuration":"0.836","delayDistrib":"Circ.easeInOut"},{"orderingFunc":"MODULO_3","durationDistrib":"Linear.easeNone","randomEase":false,"prop":"alpha","distribFunc":"Expo.easeIn","firstVal":"0.000","tweenEase":"Quad.easeIn","lastVal":"0.000","masterDelay":"0.436","firstDuration":"0.684","delayDuration":"1.325","lastDuration":"0.695","delayDistrib":"Circ.easeInOut"}],"pivot":{"y":"0.500","x":"0.500"},"randomPivotPerChar":false},
			{"multiTweens":[{"firstVal":"-107.000","randomEase":false,"lastVal":"33.000","masterDelay":"0.502","firstDuration":"0.768","delayDuration":"0.489","lastDuration":"0.629","delayDistrib":"Elastic.easeIn","orderingFunc":"MODULO_2","durationDistrib":"Sine.easeInOut","distribFunc":"Bounce.easeIn","prop":"y","tweenEase":"Quart.easeIn"},{"firstVal":"0.000","randomEase":false,"lastVal":"0.000","masterDelay":"0.003","firstDuration":"0.257","delayDuration":"1.734","lastDuration":"0.357","delayDistrib":"Back.easeInOut","orderingFunc":"RANDOM","durationDistrib":"Bounce.easeIn","distribFunc":"Quart.easeInOut","prop":"alpha","tweenEase":"Elastic.easeOut"},{"firstVal":"-22.300","randomEase":false,"lastVal":"0.050","masterDelay":"0.854","firstDuration":"0.819","delayDuration":"0.834","lastDuration":"0.718","delayDistrib":"Sine.easeInOut","orderingFunc":"SIN_2","durationDistrib":"Cubic.easeIn","distribFunc":"Sine.easeInOut","prop":"scaleX","tweenEase":"Quad.easeOut"},{"firstVal":"3942645.525","randomEase":false,"lastVal":"16013851.717","masterDelay":"0.472","firstDuration":"1.189","delayDuration":"1.603","lastDuration":"0.817","delayDistrib":"Sine.easeIn","orderingFunc":"MODULO_3","durationDistrib":"Elastic.easeInOut","distribFunc":"Bounce.easeIn","prop":"color","tweenEase":"Expo.easeIn"}],"pivot":{"y":"0.000","x":"0.000"},"randomPivotPerChar":false},
			{"randomPivotPerChar":false,"multiTweens":[{"prop":"scaleY","durationDistrib":"Circ.easeInOut","distribFunc":"Back.easeIn","tweenEase":"Cubic.easeInOut","randomEase":false,"firstVal":"-5.900","orderingFunc":"SIN_2","lastVal":"6.650","masterDelay":"0.559","firstDuration":"0.367","delayDuration":"3.758","lastDuration":"1.091","delayDistrib":"Expo.easeOut"},{"prop":"rotation","durationDistrib":"Cubic.easeOut","distribFunc":"Linear.easeInOut","tweenEase":"Elastic.easeOut","randomEase":true,"firstVal":"-10.800","orderingFunc":"LEFT_TO_RIGHT","lastVal":"0.420","masterDelay":"0.020","firstDuration":"0.825","delayDuration":"3.000","lastDuration":"0.769","delayDistrib":"Cubic.easeIn"},{"prop":"alpha","durationDistrib":"Quart.easeOut","distribFunc":"Linear.easeNone","tweenEase":"Bounce.easeIn","randomEase":false,"firstVal":"0.000","orderingFunc":"SIN_1","lastVal":"0.000","masterDelay":"0.822","firstDuration":"0.606","delayDuration":"1.404","lastDuration":"0.635","delayDistrib":"Linear.easeInOut"},{"prop":"x","durationDistrib":"Linear.easeNone","distribFunc":"Linear.easeOut","tweenEase":"Elastic.easeOut","randomEase":false,"firstVal":"-169.000","orderingFunc":"RANDOM_WORD_ORDER","lastVal":"151.000","masterDelay":"0.796","firstDuration":"1.009","delayDuration":"1.724","lastDuration":"0.857","delayDistrib":"Circ.easeInOut"},{"prop":"color","durationDistrib":"Elastic.easeOut","distribFunc":"Bounce.easeInOut","tweenEase":"Quint.easeInOut","randomEase":false,"firstVal":"8103394.845","orderingFunc":"RANDOM","lastVal":"3565158.188","masterDelay":"0.657","firstDuration":"0.732","delayDuration":"2.310","lastDuration":"0.399","delayDistrib":"Quad.easeIn"},{"prop":"scaleX","durationDistrib":"Circ.easeInOut","distribFunc":"Back.easeIn","tweenEase":"Cubic.easeInOut","randomEase":false,"firstVal":"-5.900","orderingFunc":"SIN_2","lastVal":"6.650","masterDelay":"0.559","firstDuration":"0.367","delayDuration":"3.758","lastDuration":"1.091","delayDistrib":"Expo.easeOut"}],"pivot":{"y":"0.500","x":"0.500"}},
			{"multiTweens":[{"orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Quint.easeIn","randomEase":false,"prop":"y","distribFunc":"Bounce.easeIn","firstVal":"-61.000","tweenEase":"Bounce.easeOut","lastVal":"30.000","masterDelay":"0.240","firstDuration":"0.747","delayDuration":"3.000","lastDuration":"1.161","delayDistrib":"Sine.easeIn"},{"orderingFunc":"SIN_2","durationDistrib":"Sine.easeInOut","randomEase":false,"prop":"alpha","distribFunc":"Quint.easeIn","firstVal":"0.000","tweenEase":"Expo.easeIn","lastVal":"0.000","masterDelay":"0.227","firstDuration":"0.338","delayDuration":"1.706","lastDuration":"0.454","delayDistrib":"Back.easeOut"}],"pivot":{"y":"1.930","x":"2.293"},"randomPivotPerChar":false},
			{"multiTweens":[{"firstVal":"-9.100","randomEase":false,"lastVal":"10.500","masterDelay":"0.336","firstDuration":"0.490","delayDuration":"2.862","lastDuration":"0.961","delayDistrib":"Linear.easeOut","orderingFunc":"RANDOM","durationDistrib":"Quad.easeInOut","distribFunc":"Quint.easeIn","prop":"scaleY","tweenEase":"Circ.easeInOut"},{"firstVal":"-8.250","randomEase":false,"lastVal":"8.640","masterDelay":"0.129","firstDuration":"0.367","delayDuration":"0.225","lastDuration":"0.650","delayDistrib":"Linear.easeNone","orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Quart.easeIn","distribFunc":"Quart.easeIn","prop":"rotation","tweenEase":"Quint.easeInOut"},{"firstVal":"-136.000","randomEase":false,"lastVal":"324.000","masterDelay":"0.880","firstDuration":"0.762","delayDuration":"3.000","lastDuration":"0.942","delayDistrib":"Elastic.easeOut","orderingFunc":"RANDOM_WORD_ORDER","durationDistrib":"Bounce.easeInOut","distribFunc":"Cubic.easeIn","prop":"y","tweenEase":"Bounce.easeOut"},{"firstVal":"0.000","randomEase":false,"lastVal":"0.000","masterDelay":"0.096","firstDuration":"0.551","delayDuration":"2.438","lastDuration":"0.232","delayDistrib":"Quad.easeInOut","orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Quint.easeOut","distribFunc":"Linear.easeNone","prop":"alpha","tweenEase":"Sine.easeIn"},{"firstVal":"-6.300","randomEase":false,"lastVal":"7.350","masterDelay":"0.972","firstDuration":"0.825","delayDuration":"3.000","lastDuration":"0.792","delayDistrib":"Sine.easeOut","orderingFunc":"MODULO_3","durationDistrib":"Quint.easeInOut","distribFunc":"Sine.easeIn","prop":"scaleX","tweenEase":"Quad.easeIn"},{"firstVal":"-1.080","randomEase":false,"lastVal":"11.670","masterDelay":"0.737","firstDuration":"1.045","delayDuration":"2.004","lastDuration":"0.688","delayDistrib":"Quart.easeOut","orderingFunc":"RANDOM","durationDistrib":"Quad.easeIn","distribFunc":"Quart.easeInOut","prop":"skewX","tweenEase":"Linear.easeOut"}],"pivot":{"y":"0.000","x":"0.000"},"randomPivotPerChar":false},
			{"multiTweens":[{"orderingFunc":"SQR","durationDistrib":"Quart.easeIn","randomEase":false,"prop":"scaleY","distribFunc":"Linear.easeIn","firstVal":"-11.600","tweenEase":"Bounce.easeInOut","lastVal":"11.750","masterDelay":"0.319","firstDuration":"0.812","delayDuration":"1.335","lastDuration":"0.765","delayDistrib":"Quint.easeOut"},{"orderingFunc":"SIN_1","durationDistrib":"Quad.easeOut","randomEase":false,"prop":"alpha","distribFunc":"Linear.easeNone","firstVal":"0.000","tweenEase":"Circ.easeInOut","lastVal":"0.000","masterDelay":"0.974","firstDuration":"0.281","delayDuration":"0.276","lastDuration":"0.774","delayDistrib":"Quint.easeIn"},{"orderingFunc":"SQR","durationDistrib":"Quart.easeIn","randomEase":false,"prop":"scaleX","distribFunc":"Linear.easeIn","firstVal":"-10.900","tweenEase":"Bounce.easeInOut","lastVal":"12.450","masterDelay":"0.319","firstDuration":"0.812","delayDuration":"1.335","lastDuration":"0.765","delayDistrib":"Quint.easeOut"},{"orderingFunc":"RANDOM_WORD_ORDER","durationDistrib":"Quart.easeOut","randomEase":true,"prop":"color","distribFunc":"Quad.easeOut","firstVal":"11257511.265","tweenEase":"Cubic.easeInOut","lastVal":"12549356.820","masterDelay":"0.072","firstDuration":"0.253","delayDuration":"0.524","lastDuration":"0.715","delayDistrib":"Sine.easeInOut"}],"pivot":{"y":"2.030","x":"2.068"},"randomPivotPerChar":false},
			{"multiTweens":[{"orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Linear.easeInOut","randomEase":false,"prop":"scaleY","distribFunc":"Sine.easeInOut","firstVal":"-18.550","tweenEase":"Quart.easeInOut","lastVal":"5.300","masterDelay":"0.241","firstDuration":"1.045","delayDuration":"2.445","lastDuration":"1.104","delayDistrib":"Cubic.easeInOut"},{"orderingFunc":"RANDOM","durationDistrib":"Back.easeInOut","randomEase":false,"prop":"y","distribFunc":"Quint.easeOut","firstVal":"-103.000","tweenEase":"Sine.easeInOut","lastVal":"341.000","masterDelay":"0.289","firstDuration":"0.640","delayDuration":"0.957","lastDuration":"0.705","delayDistrib":"Elastic.easeOut"},{"orderingFunc":"SIN_1","durationDistrib":"Bounce.easeInOut","randomEase":true,"prop":"alpha","distribFunc":"Quad.easeInOut","firstVal":"0.000","tweenEase":"Quad.easeOut","lastVal":"0.000","masterDelay":"0.170","firstDuration":"0.205","delayDuration":"0.070","lastDuration":"0.466","delayDistrib":"Circ.easeOut"},{"orderingFunc":"RIGHT_TO_LEFT","durationDistrib":"Linear.easeInOut","randomEase":false,"prop":"scaleX","distribFunc":"Sine.easeInOut","firstVal":"-18.550","tweenEase":"Quart.easeInOut","lastVal":"5.300","masterDelay":"0.241","firstDuration":"1.045","delayDuration":"2.445","lastDuration":"1.104","delayDistrib":"Cubic.easeInOut"},{"orderingFunc":"SQR","durationDistrib":"Bounce.easeIn","randomEase":true,"prop":"x","distribFunc":"Cubic.easeOut","firstVal":"-110.000","tweenEase":"Expo.easeIn","lastVal":"279.000","masterDelay":"0.475","firstDuration":"0.479","delayDuration":"3.000","lastDuration":"0.732","delayDistrib":"Quad.easeIn"},{"orderingFunc":"SIN_1","durationDistrib":"Quart.easeIn","randomEase":false,"prop":"color","distribFunc":"Cubic.easeIn","firstVal":"16039017.540","tweenEase":"Linear.easeNone","lastVal":"13950254.273","masterDelay":"0.501","firstDuration":"0.625","delayDuration":"0.956","lastDuration":"0.452","delayDistrib":"Linear.easeNone"}],"pivot":{"y":"0.500","x":"0.500"},"randomPivotPerChar":false},
			{"randomPivotPerChar":false,"multiTweens":[{"prop":"alpha","durationDistrib":"Sine.easeOut","distribFunc":"Linear.easeInOut","tweenEase":"Linear.easeIn","randomEase":false,"firstVal":"0.000","orderingFunc":"SIN_1","lastVal":"0.000","masterDelay":"0.140","firstDuration":"0.593","delayDuration":"0.352","lastDuration":"0.466","delayDistrib":"Expo.easeOut"},{"prop":"x","durationDistrib":"Sine.easeIn","distribFunc":"Cubic.easeOut","tweenEase":"Back.easeInOut","randomEase":false,"firstVal":"-171.000","orderingFunc":"MODULO_2","lastVal":"13.000","masterDelay":"0.959","firstDuration":"0.486","delayDuration":"0.106","lastDuration":"0.475","delayDistrib":"Quad.easeInOut"},{"prop":"y","durationDistrib":"Circ.easeInOut","distribFunc":"Cubic.easeIn","tweenEase":"Expo.easeInOut","randomEase":false,"firstVal":"-140.000","orderingFunc":"MODULO_2","lastVal":"217.000","masterDelay":"0.669","firstDuration":"0.737","delayDuration":"0.645","lastDuration":"0.899","delayDistrib":"Cubic.easeInOut"},{"prop":"scaleX","durationDistrib":"Circ.easeInOut","distribFunc":"Circ.easeIn","tweenEase":"Quart.easeIn","randomEase":false,"firstVal":"-0.550","orderingFunc":"RIGHT_TO_LEFT","lastVal":"32.150","masterDelay":"0.660","firstDuration":"0.234","delayDuration":"0.204","lastDuration":"0.859","delayDistrib":"Elastic.easeIn"}],"pivot":{"y":"1.503","x":"2.172"}},
			{"randomPivotPerChar":false,"multiTweens":[{"prop":"scaleY","durationDistrib":"Linear.easeNone","distribFunc":"Expo.easeInOut","tweenEase":"Bounce.easeOut","randomEase":false,"firstVal":"-33.400","orderingFunc":"RANDOM_WORD_ORDER","lastVal":"32.800","masterDelay":"0.618","firstDuration":"0.750","delayDuration":"3.000","lastDuration":"1.039","delayDistrib":"Back.easeOut"},{"prop":"rotation","durationDistrib":"Quart.easeOut","distribFunc":"Linear.easeIn","tweenEase":"Quad.easeOut","randomEase":false,"firstVal":"-8.100","orderingFunc":"LEFT_TO_RIGHT","lastVal":"5.010","masterDelay":"0.780","firstDuration":"0.726","delayDuration":"2.571","lastDuration":"0.874","delayDistrib":"Quint.easeInOut"},{"prop":"alpha","durationDistrib":"Linear.easeInOut","distribFunc":"Sine.easeInOut","tweenEase":"Back.easeInOut","randomEase":false,"firstVal":"0.000","orderingFunc":"RIGHT_TO_LEFT","lastVal":"0.000","masterDelay":"0.096","firstDuration":"0.699","delayDuration":"2.878","lastDuration":"0.382","delayDistrib":"Sine.easeOut"},{"prop":"x","durationDistrib":"Back.easeInOut","distribFunc":"Cubic.easeInOut","tweenEase":"Quint.easeInOut","randomEase":true,"firstVal":"-130.000","orderingFunc":"MODULO_2","lastVal":"319.000","masterDelay":"0.846","firstDuration":"0.249","delayDuration":"3.416","lastDuration":"0.570","delayDistrib":"Linear.easeNone"},{"prop":"scaleX","durationDistrib":"Linear.easeNone","distribFunc":"Expo.easeInOut","tweenEase":"Bounce.easeOut","randomEase":false,"firstVal":"-33.400","orderingFunc":"RANDOM_WORD_ORDER","lastVal":"32.800","masterDelay":"0.618","firstDuration":"0.750","delayDuration":"3.000","lastDuration":"1.039","delayDistrib":"Back.easeOut"}],"pivot":{"y":"0.500","x":"0.500"}},
			{"pivot":{"y":"0.500","x":"0.500"},"multiTweens":[{"distribFunc":"Elastic.easeIn","tweenEase":"Expo.easeIn","firstVal":"-7.100","randomEase":false,"lastVal":"0.150","masterDelay":"0.578","firstDuration":"0.684","delayDuration":"1.871","lastDuration":"1.098","delayDistrib":"Bounce.easeOut","orderingFunc":"MODULO_3","prop":"scaleY","durationDistrib":"Bounce.easeInOut"},{"distribFunc":"Back.easeIn","tweenEase":"Cubic.easeIn","firstVal":"-5.250","randomEase":false,"lastVal":"6.270","masterDelay":"0.061","firstDuration":"0.545","delayDuration":"3.000","lastDuration":"0.608","delayDistrib":"Circ.easeInOut","orderingFunc":"RANDOM","prop":"rotation","durationDistrib":"Expo.easeInOut"},{"distribFunc":"Back.easeOut","tweenEase":"Bounce.easeInOut","firstVal":"0.000","randomEase":false,"lastVal":"0.000","masterDelay":"0.113","firstDuration":"0.201","delayDuration":"0.975","lastDuration":"0.247","delayDistrib":"Linear.easeOut","orderingFunc":"MODULO_3","prop":"alpha","durationDistrib":"Cubic.easeIn"},{"distribFunc":"Elastic.easeIn","tweenEase":"Expo.easeIn","firstVal":"-7.100","randomEase":false,"lastVal":"0.150","masterDelay":"0.578","firstDuration":"0.684","delayDuration":"1.871","lastDuration":"1.098","delayDistrib":"Bounce.easeOut","orderingFunc":"MODULO_3","prop":"scaleX","durationDistrib":"Bounce.easeInOut"},{"distribFunc":"Linear.easeInOut","tweenEase":"Sine.easeInOut","firstVal":"4185915.143","randomEase":false,"lastVal":"3984588.563","masterDelay":"0.846","firstDuration":"0.399","delayDuration":"1.232","lastDuration":"0.863","delayDistrib":"Bounce.easeIn","orderingFunc":"LEFT_TO_RIGHT","prop":"color","durationDistrib":"Quad.easeIn"}],"randomPivotPerChar":false},
			{"pivot":{"y":"0.000","x":"0.000"},"multiTweens":[{"tweenEase":"Circ.easeInOut","firstVal":"0.000","prop":"alpha","randomEase":false,"lastVal":"0.100","masterDelay":"0.000","firstDuration":"0.300","durationDistrib":"Elastic.easeOut","lastDuration":"0.500","delayDistrib":"Sine.easeInOut","delayDuration":"0.000","orderingFunc":"LEFT_TO_RIGHT","distribFunc":"Circ.easeInOut"},{"tweenEase":"Back.easeInOut","firstVal":"10.350","prop":"scaleX","randomEase":false,"lastVal":"10.100","masterDelay":"0.474","firstDuration":"0.798","durationDistrib":"Quart.easeIn","lastDuration":"0.809","delayDistrib":"Linear.easeNone","delayDuration":"1.377","orderingFunc":"RANDOM_WORD_ORDER","distribFunc":"Back.easeInOut"}],"randomPivotPerChar":false},
			{"multiTweens":[{"firstVal":"-12.060","randomEase":true,"lastVal":"11.940","masterDelay":"0.138","firstDuration":"0.591","delayDuration":"2.479","lastDuration":"0.329","delayDistrib":"Elastic.easeOut","orderingFunc":"SIN_1","durationDistrib":"Expo.easeInOut","distribFunc":"Quint.easeIn","prop":"rotation","tweenEase":"Quint.easeIn"},{"firstVal":"-141.000","randomEase":false,"lastVal":"137.000","masterDelay":"0.587","firstDuration":"0.228","delayDuration":"1.994","lastDuration":"0.623","delayDistrib":"Circ.easeInOut","orderingFunc":"MODULO_3","durationDistrib":"Back.easeIn","distribFunc":"Sine.easeInOut","prop":"y","tweenEase":"Sine.easeInOut"},{"firstVal":"0.000","randomEase":true,"lastVal":"0.000","masterDelay":"0.723","firstDuration":"0.336","delayDuration":"3.000","lastDuration":"0.386","delayDistrib":"Circ.easeOut","orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Cubic.easeInOut","distribFunc":"Quart.easeOut","prop":"alpha","tweenEase":"Quart.easeOut"},{"firstVal":"-16.750","randomEase":false,"lastVal":"8.850","masterDelay":"0.675","firstDuration":"0.342","delayDuration":"3.000","lastDuration":"0.735","delayDistrib":"Sine.easeOut","orderingFunc":"SIN_2","durationDistrib":"Quart.easeIn","distribFunc":"Bounce.easeOut","prop":"scaleX","tweenEase":"Bounce.easeOut"}],"pivot":{"y":"0.000","x":"0.000"},"randomPivotPerChar":false},
			{"multiTweens":[{"orderingFunc":"RANDOM","durationDistrib":"Cubic.easeInOut","randomEase":false,"prop":"y","distribFunc":"Quint.easeInOut","firstVal":"-176.000","tweenEase":"Bounce.easeInOut","lastVal":"459.000","masterDelay":"0.210","firstDuration":"1.172","delayDuration":"2.208","lastDuration":"0.849","delayDistrib":"Elastic.easeOut"},{"orderingFunc":"SQR","durationDistrib":"Quint.easeOut","randomEase":false,"prop":"alpha","distribFunc":"Expo.easeInOut","firstVal":"0.000","tweenEase":"Circ.easeOut","lastVal":"0.000","masterDelay":"0.968","firstDuration":"0.466","delayDuration":"2.217","lastDuration":"0.688","delayDistrib":"Sine.easeIn"}],"pivot":{"y":"0.500","x":"0.500"},"randomPivotPerChar":false},
			{"multiTweens":[{"orderingFunc":"MODULO_3","durationDistrib":"Expo.easeIn","randomEase":false,"prop":"scaleY","distribFunc":"Bounce.easeIn","firstVal":"-16.400","tweenEase":"Quart.easeIn","lastVal":"33.000","masterDelay":"0.857","firstDuration":"0.950","delayDuration":"0.142","lastDuration":"1.186","delayDistrib":"Elastic.easeOut"},{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Expo.easeOut","randomEase":false,"prop":"alpha","distribFunc":"Quad.easeIn","firstVal":"0.000","tweenEase":"Circ.easeOut","lastVal":"0.000","masterDelay":"0.304","firstDuration":"0.549","delayDuration":"0.507","lastDuration":"0.283","delayDistrib":"Cubic.easeOut"},{"orderingFunc":"LEFT_TO_RIGHT","durationDistrib":"Elastic.easeIn","randomEase":false,"prop":"color","distribFunc":"Sine.easeInOut","firstVal":"4605345.518","tweenEase":"Sine.easeInOut","lastVal":"2290089.848","masterDelay":"0.869","firstDuration":"0.650","delayDuration":"1.644","lastDuration":"0.367","delayDistrib":"Quint.easeInOut"}],"pivot":{"y":"1.949","x":"1.751"},"randomPivotPerChar":false},
			{"randomPivotPerChar":false,"multiTweens":[{"prop":"scaleY","durationDistrib":"Circ.easeOut","distribFunc":"Quart.easeOut","tweenEase":"Sine.easeOut","randomEase":false,"firstVal":"-15.800","orderingFunc":"RIGHT_TO_LEFT","lastVal":"35.700","masterDelay":"0.165","firstDuration":"0.486","delayDuration":"2.683","lastDuration":"0.709","delayDistrib":"Quint.easeIn"},{"prop":"skewX","durationDistrib":"Linear.easeNone","distribFunc":"Linear.easeIn","tweenEase":"Circ.easeInOut","randomEase":false,"firstVal":"-0.990","orderingFunc":"SIN_1","lastVal":"6.480","masterDelay":"0.436","firstDuration":"0.678","delayDuration":"2.028","lastDuration":"0.386","delayDistrib":"Quad.easeOut"},{"prop":"alpha","durationDistrib":"Linear.easeIn","distribFunc":"Expo.easeIn","tweenEase":"Back.easeInOut","randomEase":false,"firstVal":"0.000","orderingFunc":"RIGHT_TO_LEFT","lastVal":"0.000","masterDelay":"0.426","firstDuration":"0.458","delayDuration":"3.922","lastDuration":"0.374","delayDistrib":"Quad.easeIn"},{"prop":"x","durationDistrib":"Back.easeIn","distribFunc":"Circ.easeOut","tweenEase":"Bounce.easeInOut","randomEase":false,"firstVal":"-116.000","orderingFunc":"RIGHT_TO_LEFT","lastVal":"45.000","masterDelay":"0.588","firstDuration":"0.359","delayDuration":"3.000","lastDuration":"1.054","delayDistrib":"Circ.easeOut"},{"prop":"y","durationDistrib":"Quad.easeInOut","distribFunc":"Sine.easeOut","tweenEase":"Sine.easeIn","randomEase":false,"firstVal":"-96.000","orderingFunc":"SQR","lastVal":"56.000","masterDelay":"0.408","firstDuration":"0.697","delayDuration":"2.004","lastDuration":"0.756","delayDistrib":"Back.easeIn"},{"prop":"color","durationDistrib":"Back.easeIn","distribFunc":"Cubic.easeOut","tweenEase":"Cubic.easeInOut","randomEase":false,"firstVal":"4345298.685","orderingFunc":"RANDOM_WORD_ORDER","lastVal":"9319742.932","masterDelay":"0.756","firstDuration":"0.614","delayDuration":"3.516","lastDuration":"0.363","delayDistrib":"Circ.easeOut"},{"prop":"scaleX","durationDistrib":"Circ.easeOut","distribFunc":"Quart.easeOut","tweenEase":"Sine.easeOut","randomEase":false,"firstVal":"-15.800","orderingFunc":"RIGHT_TO_LEFT","lastVal":"35.700","masterDelay":"0.165","firstDuration":"0.486","delayDuration":"2.683","lastDuration":"0.709","delayDistrib":"Quint.easeIn"}],"pivot":{"y":"0.500","x":"0.500"}},
			{"pivot":{"y":"0.000","x":"0.000"},"multiTweens":[{"tweenEase":"Quad.easeIn","firstVal":"0.000","prop":"alpha","randomEase":false,"lastVal":"0.000","masterDelay":"0.421","firstDuration":"0.642","durationDistrib":"Circ.easeOut","lastDuration":"0.429","delayDistrib":"Linear.easeIn","delayDuration":"2.188","orderingFunc":"RANDOM_WORD_ORDER","distribFunc":"Quad.easeIn"}],"randomPivotPerChar":false},
			{"multiTweens":[{"orderingFunc":"RANDOM","durationDistrib":"Back.easeIn","randomEase":false,"prop":"scaleY","distribFunc":"Linear.easeInOut","firstVal":"-0.100","tweenEase":"Sine.easeInOut","lastVal":"36.050","masterDelay":"0.793","firstDuration":"0.669","delayDuration":"3.000","lastDuration":"0.236","delayDistrib":"Quad.easeOut"},{"orderingFunc":"RANDOM_WORD_ORDER","durationDistrib":"Bounce.easeOut","randomEase":true,"prop":"y","distribFunc":"Quart.easeIn","firstVal":"-6.000","tweenEase":"Bounce.easeOut","lastVal":"137.000","masterDelay":"0.219","firstDuration":"1.131","delayDuration":"3.000","lastDuration":"0.589","delayDistrib":"Quart.easeIn"},{"orderingFunc":"RANDOM_WORD_ORDER","durationDistrib":"Bounce.easeOut","randomEase":true,"prop":"alpha","distribFunc":"Elastic.easeIn","firstVal":"0.000","tweenEase":"Quart.easeInOut","lastVal":"0.000","masterDelay":"0.411","firstDuration":"0.420","delayDuration":"4.125","lastDuration":"0.635","delayDistrib":"Back.easeIn"},{"orderingFunc":"SQR","durationDistrib":"Cubic.easeIn","randomEase":true,"prop":"x","distribFunc":"Quad.easeOut","firstVal":"-80.000","tweenEase":"Back.easeIn","lastVal":"431.000","masterDelay":"0.984","firstDuration":"0.735","delayDuration":"2.749","lastDuration":"0.771","delayDistrib":"Quint.easeOut"}],"pivot":{"y":"0.500","x":"0.500"},"randomPivotPerChar":false},
		];


		public static function previous():Object
		{
			ptr = (ptr+PRESETS.length-1)%PRESETS.length;
			return current();
		}


		public static function current():Object
		{
			return PRESETS[ptr];
		}


		public static function next():Object
		{
			ptr = ++ptr%PRESETS.length;
			return current();
		}


		public static function number():int
		{
			return PRESETS.length;
		}


		public static function getPreset(index:int):Object
		{
			return PRESETS[index];
		}


		public static function currentId():int
		{
			return ptr+1;
		}



	}
}
